/**
 * @module finance
 * Barrel export for the finance system: contracts, arbitration, payroll.
 */

export {
  // Constants
  LEAGUE_MINIMUM_SALARY,
  LUXURY_TAX_THRESHOLD,
  LUXURY_TAX_TIERS,
  PRE_ARB_MAX_YEARS,
  ARB_FIRST_YEAR,
  ARB_LAST_YEAR,
  ARB_MAX_BASE_SALARY,
  ARB_DIVISOR,
  ARB_YEAR_MULTIPLIERS,
  ARB_PERFORMANCE_VARIANCE,
  ARB_TEAM_WIN_PROBABILITY,
  SUPER_TWO_COHORT_SHARE,
  ARB_ESCALATOR_PER_WIN,
  ARB_ESCALATOR_CAP,
  MAX_CONTRACT_YEARS,
  NTC_RATING_THRESHOLD,
  PLAYER_OPTION_RATING_THRESHOLD,
  FUTURE_COMMITMENT_YEARS,
  TEAM_MARKETS,
  // Types (re-exported as values for runtime use where applicable)
  type MarketSize,
  type MarketConfig,
  type ContractDetail,
  type ArbitrationCase,
  type HoldoutEvaluation,
  type TeamPayroll,
  type ExtensionTeamContext,
  type ExtensionContractTerms,
  type ExtensionWillingness,
  type NegotiationRound,
  type ExtensionNegotiationSession,
  type ExtensionResult,
  type TeamExtensionProcessResult,
  // Functions
  calculatePlayerValue,
  qualifiesForSuperTwo,
  generateArbitrationCase,
  evaluateHoldout,
  resolveArbitration,
  calculateTeamPayroll,
  calculateLuxuryTax,
  getTeamBudget,
  advanceContracts,
  generateContractOffer,
  getArbEligiblePlayers,
  serviceDaysToYears,
  evaluateExtensionWillingness,
  calculateExtensionOffer,
  negotiateExtension,
  processTeamExtensions,
} from './contracts.js';

export {
  findComparableContracts,
  generateMarketReport,
  predictSigning,
  generateMarketSummary,
  type ComparableContract,
  type SigningPrediction,
  type MarketReportContext,
  type MarketReport,
  type MarketSummary,
} from './marketIntelligence.js';
