// Math
export {
  GameRNG,
  createGameRNG,
  computeLog5Probabilities,
} from './math/index.js';
export type {
  GameRNGState,
  Log5Input,
  Log5Modifiers,
  OutcomeRates,
} from './math/index.js';
export {
  archiveOldSeasons,
  estimateSnapshotSize,
  pruneStaleData,
} from './performance/index.js';
export { compareTimelines } from './timeline/index.js';
export {
  runSeasonCalibration,
  summarizeSeasonCalibration,
} from './calibration/index.js';
export type {
  SeasonCalibrationBattingTotals,
  SeasonCalibrationConfig,
  SeasonCalibrationResult,
  SeasonCalibrationSeason,
  SeasonCalibrationSeasonSummary,
  SeasonCalibrationSummary,
  SeasonCalibrationTeamRecord,
} from './calibration/index.js';
export {
  buildLeagueAdvancedContext,
  calculateAdvancedStatLine,
  calculateBattingAverage,
  calculateFip,
  calculateIso,
  calculateObp,
  calculateOps,
  calculateSlg,
  calculateWoba,
  calculateXfip,
  estimateProjectedWarFromGrade,
  estimateProjectedWarRange,
} from './stats/advanced.js';
export {
  ERA_PLUS_SHUTOUT_CAP,
  computeTeamBullpenEraPlus,
  computeTeamEraPlus,
  computeTeamWrcPlus,
  findLeadingHitterByWrcPlus,
  getPrimaryStarterEraPlusLines,
  rankTeamsByWrcPlus,
} from './stats/teamAggregates.js';
export {
  CAREER_MILESTONES,
  calculateMilestoneProgress,
  getMilestoneAlerts,
} from './stats/milestones.js';
export {
  CAREER_SHUTOUT_MILESTONE,
  isCompleteGameShutout,
  recordCareerShutout,
} from './stats/shutouts.js';
export {
  SEASON_GAMES,
  findNotableProjections,
  formatPaceLabel,
  projectSeasonStats,
} from './stats/projections.js';
export type {
  AdvancedStatLine,
  LeagueAdvancedContext,
  LeaderboardStatKey,
  ProjectedWarRange,
} from './stats/advanced.js';
export type {
  LeadingHitterLine,
  StarterEraPlusLine,
  TeamPitchingAggregate,
  TeamWrcPlusLine,
  TeamWrcPlusRank,
} from './stats/teamAggregates.js';
export type {
  CareerMilestoneDefinition,
  CareerStatTotals,
  MilestoneProgress,
  MilestoneAlert,
} from './stats/milestones.js';
export type {
  HitterProjectedStatLine,
  NotableProjection,
  PitcherProjectedStatLine,
  ProjectedStatLine,
  SeasonProjection,
} from './stats/projections.js';

// Moments
export {
  MOMENT_IMPACT_THRESHOLD,
  MOMENT_RELEVANCE_DECAY_RATE,
  MAX_MOMENTS_PER_PLAYER,
  PERMANENT_CLUTCH_WALK_OFF_COUNT,
  WALK_OFF_HR_IMPACT,
  NO_HITTER_IMPACT,
  PERFECT_GAME_IMPACT,
  FOUR_HR_GAME_IMPACT,
  PLAYOFF_ERROR_IMPACT,
  FIRST_CAREER_HR_IMPACT,
  FIRST_ALL_STAR_IMPACT,
  MILESTONE_500_HR_IMPACT,
  MILESTONE_3000_HIT_IMPACT,
  MILESTONE_300_WIN_IMPACT,
  BLOWN_WS_SAVE_IMPACT,
  CYCLE_IMPACT,
  TWENTY_K_GAME_IMPACT,
  BENCH_CLEARING_BRAWL_IMPACT,
  PLAYOFF_WALK_OFF_BONUS,
  WORLD_SERIES_CLINCHER_BONUS,
  PRESSURE_CLUTCH_BONUS,
  PRESSURE_SCARRED_PENALTY,
  NO_HITTER_ATTRIBUTE_BONUS,
  FOUR_HR_THRESHOLD,
  COMPLETE_GAME_OUTS,
  TWENTY_STRIKEOUT_THRESHOLD,
  MILESTONE_500_HR_THRESHOLD,
  MILESTONE_3000_HIT_THRESHOLD,
  MILESTONE_300_WIN_THRESHOLD,
  WORLD_SERIES_CLUTCH_DURATION_SEASONS,
  SCARRED_DURATION_SEASONS,
  BENCH_CLEARING_BRAWL_INTENSITY_THRESHOLD,
  BENCH_CLEARING_BRAWL_HBP_THRESHOLD,
  BENCH_CLEARING_BRAWL_MIN_INNING,
  BENCH_CLEARING_BRAWL_MAX_SCORE_MARGIN,
  detectMoment,
  applyMomentEffects,
  decayMoments,
  formatMomentDescription,
  NICKNAME_TRIGGERS,
  FLASH_WINDOW_SIZE,
  FLASH_REQUIRED_LEAGUE_LEADS,
  PROFESSOR_WINDOW_SIZE,
  PROFESSOR_RATIO_THRESHOLD,
  IRON_MAN_WINDOW_SIZE,
  IRON_MAN_GAMES_THRESHOLD,
  DOCTOR_K_STRIKEOUT_THRESHOLD,
  CARDIAC_KID_BLOWN_SAVE_THRESHOLD,
  MR_OCTOBER_PA_THRESHOLD,
  MR_OCTOBER_OPS_THRESHOLD,
  THE_KID_DEBUT_AGE_THRESHOLD,
  THE_KID_CURRENT_AGE_THRESHOLD,
  OLD_RELIABLE_AGE_THRESHOLD,
  OLD_RELIABLE_OVR_THRESHOLD,
  OLD_RELIABLE_YEARS_THRESHOLD,
  NATURAL_POTENTIAL_THRESHOLD,
  NATURAL_OVR_THRESHOLD,
  NATURAL_AGE_THRESHOLD,
  CRASH_INJURY_THRESHOLD,
  VULTURE_WIN_THRESHOLD,
  VULTURE_ERA_THRESHOLD,
  CAPTAIN_SEASONS_THRESHOLD,
  CAPTAIN_LEADERSHIP_THRESHOLD,
  GHOST_PA_THRESHOLD,
  MR_3000_HIT_THRESHOLD,
  CLOSER_SAVE_THRESHOLD,
  CLOSER_WINDOW_SIZE,
  BOOM_OR_BUST_HR_THRESHOLD,
  BOOM_OR_BUST_STRIKEOUT_THRESHOLD,
  WALL_GOLD_GLOVE_THRESHOLD,
  PHOENIX_DROP_THRESHOLD,
  PHOENIX_RECOVERY_THRESHOLD,
  FRANCHISE_WAR_THRESHOLD,
  FRANCHISE_YEARS_THRESHOLD,
  SNAKEBIT_WAR_THRESHOLD,
  evaluateNicknames,
  getNicknameDisplayText,
  CHAMPIONSHIP_RUN_IMPACT,
  CHAMPIONSHIP_RUN_RELEVANCE,
  BREAKOUT_SEASON_IMPACT,
  BREAKOUT_SEASON_RELEVANCE,
  CONTENTION_COLLAPSE_IMPACT,
  CONTENTION_COLLAPSE_RELEVANCE,
  CONTENTION_COLLAPSE_WINS_THRESHOLD,
  CONTENTION_WINDOW_OPENS_IMPACT,
  CONTENTION_WINDOW_OPENS_RELEVANCE,
  FIRST_DYNASTY_PEAK_IMPACT,
  FIRST_DYNASTY_PEAK_RELEVANCE,
  LOSING_SEASON_STREAK_IMPACT,
  LOSING_SEASON_STREAK_RELEVANCE,
  REBUILD_BEGUN_IMPACT,
  REBUILD_BEGUN_RELEVANCE,
  FIRE_SALE_IMPACT,
  FIRE_SALE_RELEVANCE,
  DYNASTY_END_IMPACT,
  DYNASTY_END_RELEVANCE,
  CURSED_FRANCHISE_IMPACT,
  CURSED_FRANCHISE_RELEVANCE,
  VETERAN_CORE_RETIRES_IMPACT,
  VETERAN_CORE_RETIRES_RELEVANCE,
  SEPTEMBER_HEROICS_IMPACT,
  SEPTEMBER_HEROICS_RELEVANCE,
  PLAYOFF_GAUNTLET_IMPACT,
  PLAYOFF_GAUNTLET_RELEVANCE,
  DOMINANT_ROTATION_IMPACT,
  DOMINANT_ROTATION_RELEVANCE,
  BULLPEN_COLLAPSE_IMPACT,
  BULLPEN_COLLAPSE_RELEVANCE,
  LINEUP_OF_ERA_IMPACT,
  LINEUP_OF_ERA_RELEVANCE,
  COMEBACK_PLAYER_IMPACT,
  COMEBACK_PLAYER_MISSED_GAMES_THRESHOLD,
  COMEBACK_PLAYER_RELEVANCE,
  COMEBACK_PLAYER_WAR_THRESHOLD,
  REDEMPTION_ARC_IMPACT,
  REDEMPTION_ARC_RELEVANCE,
  LATE_CAREER_PEAK_IMPACT,
  LATE_CAREER_PEAK_RELEVANCE,
  ROOKIE_BREAKOUT_IMPACT,
  ROOKIE_BREAKOUT_RELEVANCE,
  ROOKIE_SENSATION_IMPACT,
  ROOKIE_SENSATION_RELEVANCE,
  INJURY_RETURN_HERO_IMPACT,
  INJURY_RETURN_HERO_RELEVANCE,
  INJURY_RETURN_HERO_MIN_OPS_OR_ERA_PLUS,
  INJURY_RETURN_HERO_WINDOW_DAYS,
  INJURY_RETURN_HERO_MIN_PA,
  INJURY_RETURN_HERO_MIN_IP_OUTS,
  TRADE_DEADLINE_SPARK_IMPACT,
  TRADE_DEADLINE_SPARK_RELEVANCE,
  TRADE_DEADLINE_SPARK_MIN_OPS_OR_ERA_PLUS,
  TRADE_DEADLINE_SPARK_WINDOW_DAYS,
  TRADE_DEADLINE_SPARK_MIN_PA,
  TRADE_DEADLINE_SPARK_MIN_IP_OUTS,
  SEPTEMBER_CALLUP_HERO_IMPACT,
  SEPTEMBER_CALLUP_HERO_RELEVANCE,
  SEPTEMBER_CALLUP_HERO_MIN_OPS_OR_ERA_PLUS,
  SEPTEMBER_CALLUP_HERO_WINDOW_DAYS,
  SEPTEMBER_CALLUP_HERO_MIN_PA,
  SEPTEMBER_CALLUP_HERO_MIN_IP_OUTS,
  buildTeamSeasonSummaries,
  detectWeeklyMoments,
  estimatedWar,
  detectCursedFranchise,
  detectBreakoutSeason,
  detectBullpenCollapse,
  detectChampionshipRun,
  detectContentionWindowOpens,
  detectContentionCollapse,
  detectDominantRotation,
  detectEraEndingCollapse,
  detectDynastyEnd,
  detectFireSale,
  detectFirstDynastyPeak,
  detectLineupOfEra,
  detectLosingSeasonStreak,
  detectPerennialContender,
  detectPlayoffGauntlet,
  detectRivalryRenewed,
  detectRebuildBegun,
  resolvePlayoffTeamIds,
  detectSeptemberHeroics,
  detectSeasonIdentityMoments,
  detectThreePeat,
  detectVeteranCoreRetires,
  detectComebackPlayer,
  detectInjuryReturnHero,
  detectLateCareerPeak,
  detectRedemptionArc,
  detectRookieBreakout,
  detectRookieSensation,
  detectSeptemberCallupHero,
  detectTradeDeadlineSpark,
} from './moments/index.js';
export type {
  MomentType as SignatureMomentType,
  MomentRound,
  Moment as SignatureMoment,
  CareerTotalsBeforeGame,
  MomentDetectionContext,
  DetectedMoment,
  MomentHistoryUpdate,
  MomentEffectModifiers,
  NicknameId,
  NicknameTrigger,
  NicknameCareerBattingStats,
  NicknameCareerPitchingStats,
  NicknameCareerPlayoffBattingStats,
  NicknameCareerStats,
  NicknameSeasonHistoryEntry,
  EarnedNickname,
  NicknameEvaluation,
  BuildTeamSeasonSummariesContext,
  InjuryReturnHeroDetectionContext,
  SeptemberCallupHeroDetectionContext,
  TeamSeasonSummary,
  SeasonIdentityMomentDetectionContext,
  SeasonIdentityDetectedMoment,
  SignatureMomentDetectionResult,
  TradeDeadlineSparkDetectionContext,
  WeeklyDetectedMoment,
  WeeklyMomentDetectionContext,
} from './moments/index.js';

// Player
export {
  toDisplayRating,
  toInternalRating,
  toLetterGrade,
  hitterOverall,
  pitcherOverall,
  clampRating,
  RATING_MIN,
  RATING_MAX,
  DISPLAY_MIN,
  DISPLAY_MAX,
  GRADE_THRESHOLDS,
  HITTER_WEIGHTS,
  PITCHER_WEIGHTS,
  generatePlayer,
  generateTeamRoster,
  generateLeaguePlayers,
  HITTER_POSITIONS,
  PITCHER_POSITIONS,
  ALL_POSITIONS,
  ROSTER_LEVELS,
  DEV_PHASES,
  comparePlayersHead2Head,
  comparePlayerStats,
  rankPlayerAttributes,
  generateComparisonSummary,
  findSimilarPlayers,
  getPlayerArchetype,
} from './player/index.js';
export type {
  HitterAttributes,
  PitcherAttributes,
  LetterGrade,
  Position,
  RosterLevel,
  DevPhase,
  DevelopmentProgram,
  DevelopmentTrajectory,
  NoTradeClauseType,
  DeferredMoneyInstallment,
  ExtensionHistoryEntry,
  GeneratedPlayer,
  AttributeComparison,
  ComparisonResult,
  RankedAttribute,
  StatComparison,
  SimilarPlayer,
  SimilarityResult,
  PlayerArchetype,
} from './player/index.js';
export {
  assignPlayerToTeam,
  getLongestTeamTenureSeasons,
  getTenureSeasonCount,
  releasePlayerFromTeam,
  retirePlayerFromTeam,
  seedInitialTeamTenure,
} from './player/index.js';
export {
  PERSONALITY_TRAITS,
  POSITIVE_CHEMISTRY_TRAITS,
  NEGATIVE_CHEMISTRY_TRAITS,
  CLUBHOUSE_LEADER_TRAITS,
  PLAYOFF_COMPOSURE_TRAITS,
  VOLATILE_PERFORMANCE_TRAITS,
  assignPersonalityTraits,
  deriveDeterministicPersonalityTraits,
  calculatePlayoffComposureModifier,
  countMatchingTraits,
  detectProspectBreakouts,
  COACH_ROLES,
  COACH_SPECIALTIES,
  calculateCoachMarketValue,
  calculateCoachingPayroll,
  calculateStaffBudget,
  fireCoach,
  generateCoachFreeAgents,
  generateCoachingStaff,
  getBreakoutProbability,
  getCoachSpecialtyForPosition,
  getCoachingDevelopmentModifier,
  getPositionConversionTargets,
  hireCoach,
  initializePlayerDevelopmentProfile,
  createProspectBond,
  getProspectLoyaltyModifier,
  updateProspectBonds,
  applyDevelopmentSetback,
  checkDevelopmentSetback,
  recoverDevelopmentSetback,
  isDevelopmentSetbackExpired,
  reconcileDevelopmentPipeline,
  runMonthlyDevelopmentCheckpoint,
  calculateCoachSynergy,
  calculateCoachPlayerAffinity,
  calculateStaffHarmony,
  getCoachDevelopmentBonus,
  identifyChemistryIssues,
  findMentorCandidates,
  findProtegeeCandidates,
  pairMentors,
  advanceMentorship,
  getMentorshipDevelopmentBonus,
  toMentorRelationship,
  fromMentorRelationship,
} from './player/index.js';
export type {
  BreakoutEvent,
  CoachRole,
  CoachSpecialty,
  Coach,
  ProspectBondSnapshot,
  CoachSynergy,
  CoachPlayerAffinity,
  StaffHarmony,
  ChemistryIssue,
  MentorshipPairing,
  MentorshipEvent,
} from './player/index.js';
export {
  calculateBreakoutProbability,
  classifyDevelopmentTrajectory,
  detectRegressionRisk,
  generateBreakoutScoutReport,
  predictProspectCeiling,
} from './player/breakoutEngine.js';
export type {
  BreakoutAssessment,
  BreakoutDevelopmentTrajectory,
  BreakoutFactor,
  BreakoutRiskLevel,
  BreakoutSeasonHistoryEntry,
  CeilingConfidenceLevel,
  CeilingProjection,
  RegressionAssessment,
  RegressionRiskLevel,
} from './player/breakoutEngine.js';

// League
export {
  TEAMS,
  DIVISIONS,
  getTeamsByDivision,
  getTeamById,
  StandingsTracker,
  generateSchedule,
  getGamesForDay,
  getSeasonLength,
  isDivisionGame,
} from './league/index.js';
export type {
  Division,
  OwnerArchetype,
  TeamDef,
  TeamRecord,
  StandingsEntry,
  ScheduledGame,
} from './league/index.js';
export {
  getPersonalityArchetype,
  createInitialPlayerMorale,
  applyMoraleEvent,
  calculateTeamChemistry,
  chemistryScoreToModifier,
  createOwnerState,
  evaluateOwnerState,
  applyOwnerDecisionDelta,
  createFrontOfficeState,
  evaluateFrontOfficeState,
  frontOfficeTradeModifier,
  frontOfficeFreeAgencyAppeal,
  buildFrontOfficeBriefing,
  calculateAwardRaces,
  buildRookieOfTheYearVotingEntries,
  finalizeAwardResults,
  AWARD_NAMES,
  generateAwardNarrative,
  generateAwardCeremony,
  getRivalry,
  seedHistoricalRivalries,
  upsertRivalry,
  recordRivalryGame,
  deriveRivalriesFromStandings,
  finalizeSeasonRivalries,
  recordBlockbusterTradeRivalry,
  recordStarDefectionRivalry,
  rivalryTradePenalty,
  rivalryGameModifier,
  computeRivalryIntensityScore,
  backfillLegacyRecordBook,
  getRecordWatchList,
  updateRecordBook,
  evaluateHOFCandidate,
  processHOFInductions,
  calculateDynastyScore,
  ACHIEVEMENT_DEFINITIONS,
  checkAchievements,
  RELATIONSHIP_TIER_THRESHOLDS,
  GRUDGE_DECAY_RATE,
  PERMANENT_DECAY_RATE,
  MAX_TRADE_HISTORY,
  MAX_TRADE_PENALTY_PCT,
  createRelationshipMap,
  getRelationship,
  modifyRelationship,
  decayRelationships,
  getRelationshipTier,
  getTradeValueAdjustment,
  addTradeMemory,
  generateRelationshipTooltip,
  adjustFABidForRelationship,
  shouldPassOnWaiverClaim,
  adjustDraftPickTradeValue,
  getRule5TargetingBonus,
  generateRelationshipEffectNarrative,
} from './league/index.js';
export type {
  AchievementCategory,
  AchievementDefinition,
  AchievementMetricMap,
  AchievementProgressValue,
  AchievementUnlockResult,
  CheckAchievementsArgs,
  CheckAchievementsResult,
  RelationshipEventType,
  RelationshipTier,
  TradeMemory,
  RelationshipEvent,
  GMRelationship,
  RelationshipEffect,
  PersonalityArchetype,
  MoraleEvent,
  OwnerEvaluationContext,
  BriefingContext,
  TeamChemistryContext,
  FrontOfficeEvaluationContext,
  BrokenRecord,
  LegacyRecordBookArgs,
  PlayerSeasonRecord,
  RecordWatchArgs,
  TeamStandingRecord,
  UpdateRecordBookArgs,
  AwardRaceEntry,
  AwardRaces,
  AwardReactionTone,
  AwardNarrativeContext,
  AwardNarrative,
  AwardCeremonyScript,
  ComputedRivalryIntensityContext,
  RivalrySeasonReviewContext,
  RivalryTradeContext,
  RivalryDefectionContext,
  CareerBattingTotals,
  CareerPitchingTotals,
  CareerStatsLedger,
  HallOfFameCandidate,
  HallOfFameEvaluation,
  HallOfFameEntry,
  HallOfFameBallotEntry,
  ProcessHOFInductionsArgs,
  ProcessHOFInductionsResult,
  FranchiseTimelineEntry,
  DynastyScoreSummary,
} from './league/index.js';

// Sim
export {
  initializeGMCareer,
  recordSeasonResult,
  processGMFiring,
  applyForJob,
  getCareerLegacyScore,
  generateJobMarket,
} from './career/index.js';
export type {
  CareerStandingsEntry,
  GMCareer,
  GMCareerEntry,
  JobMarket,
  JobOpening,
} from './career/index.js';
export {
  REGULAR_SEASON_DAYS,
  REGULAR_SEASON_MONTHS,
  getRegularSeasonGameDays,
  getDaysUntilTradeDeadline,
  getRegularSeasonMonthForDay,
  getTradeDeadlineDay,
  getNextMonthStartDay,
  isTradeDeadlineModeDay,
  resolvePlateAppearance,
  advanceRunners,
  freshRunnerState,
  simulateGame,
  createSeasonState,
  simulateDay,
  simulateWeek,
  simulateMonth,
  buildPlayoffPreview,
  determinePlayoffSeeds,
  initializePlayoffBracket,
  simPlayoffGame,
  simNextPlayoffGame,
  simPlayoffSeries,
  simPlayoffRound,
  advancePlayoffRound,
  isPlayoffComplete,
  simulateSeries,
  simulatePlayoffs,
} from './sim/index.js';
export type {
  RegularSeasonMonth,
  PAOutcome,
  PAContext,
  PAResult,
  BaseState,
  RunnerState,
  MarkovResult,
  GameTeam,
  GameBoxScore,
  PlayerGameStats,
  SeasonState,
  DaySimResult,
  LeagueId,
  PlayoffSeed,
  PlayoffKeyPerformer,
  PlayoffGameResult,
  PlayoffSeriesState,
  CompletedRoundResult,
  PlayoffPreviewSeries,
  PlayoffPreviewTeamSlot,
  SeriesResult,
  PlayoffRound,
  PlayoffBracket,
} from './sim/index.js';
export {
  buildPlayoffGameModifiers,
  calculateHomeFieldAdvantage,
  calculateMustWinPressure,
  calculatePitcherFatigue,
  calculateStreakMomentum,
  generateMomentumNarrative,
} from './sim/playoffMomentum.js';
export type {
  FatigueResult,
  GameModifiers,
  PlayoffGameContext,
  PressureModifier,
} from './sim/playoffMomentum.js';

// Player Development
export {
  developPlayer,
  developAllPlayers,
  updateDevPhase,
  shouldRetire,
  growMentalToughness,
} from './player/index.js';
export type { DevProgram } from './player/index.js';

// Injuries
export {
  checkInjury,
  advanceInjury,
  getInjuryMultiplier,
  generateInjury,
  describeInjury,
  processInjuries,
} from './player/index.js';
export type {
  InjuryType,
  InjurySeverity,
  Injury,
} from './player/index.js';

// Finance
export {
  LEAGUE_MINIMUM_SALARY,
  LUXURY_TAX_THRESHOLD,
  TEAM_MARKETS,
  SUPER_TWO_COHORT_SHARE,
  ARB_ESCALATOR_PER_WIN,
  ARB_ESCALATOR_CAP,
  calculatePlayerValue,
  qualifiesForSuperTwo,
  generateArbitrationCase,
  evaluateHoldout,
  resolveArbitration,
  calculateTeamPayroll,
  calculateLuxuryTax,
  getTeamBudget,
  advanceContracts,
  generateContractOffer,
  getArbEligiblePlayers,
  serviceDaysToYears,
  evaluateExtensionWillingness,
  calculateExtensionOffer,
  negotiateExtension,
  processTeamExtensions,
  findComparableContracts,
  generateMarketReport,
  predictSigning,
  generateMarketSummary,
} from './finance/index.js';
export type {
  ContractDetail,
  ArbitrationCase,
  HoldoutEvaluation,
  TeamPayroll,
  ExtensionTeamContext,
  ExtensionContractTerms,
  ExtensionWillingness,
  NegotiationRound,
  ExtensionNegotiationSession,
  ExtensionResult,
  TeamExtensionProcessResult,
  ComparableContract,
  SigningPrediction,
  MarketReportContext,
  MarketReport,
  MarketSummary,
} from './finance/index.js';

// Onboarding
export {
  AGM_CANDIDATES,
  analyzePayrollBreakdown,
  buildDayOneDefaults,
  buildDayOneImpacts,
  buildDayOneNarrativePack,
  buildDayOneOrgReview,
  buildDayOneTeamCard,
  buildDayOneTeaser,
  buildOpeningDayPlan,
  CHAPTER_ORDER,
  ONBOARDING_MODE,
  ONBOARDING_CHAPTER_IDS,
  pickDayOneCrisis,
  REVISED_CHAPTER_ORDER,
  analyzeLineupStrengths,
  advanceChapter,
  advanceRevisedChapter,
  assessFarmSystem,
  assessPipelineHealth,
  assessRoster,
  assessStaffStrengths,
  applyScoutingHire,
  applyStaffHires,
  calculateFinancialFlexibility,
  completeChapter,
  createOnboardingState,
  createRevisedOnboardingState,
  evaluateCoachingStaff,
  generateAssistantGM,
  generateChapterIntro,
  generateChapterScript,
  generateChapterTransition,
  generateFarmReaction,
  generateFarmNarrative,
  generateFarewell,
  generateChapterTips,
  generateDecisionExplanation,
  generateFinancialReaction,
  generateFinancialPlaybook,
  generateFullOnboardingScript,
  generateGreeting,
  generateOnboardingOpeningStatementOptions,
  generateOnboardingPressConference,
  generateOnboardingHighlights,
  generateRevisedOnboardingScript,
  ROUND_THREE_DIALOGUE,
  generateScoutingHiringSlate,
  generateBudgetOverview,
  generateOwnerReaction,
  generateOwnerMeeting,
  generatePressReaction,
  generateQuickReference,
  reactToDevelopmentStyle,
  reactToMediaTone,
  reactToScoutingFocus,
  reactToSeasonGoal,
  reactToSpendingStyle,
  reactToTradeApproach,
  generateRosterReaction,
  generateScoutingBriefing,
  generateScoutingReaction,
  generateSeasonStrategy,
  generateStaffHiringSlate,
  generateStaffReaction,
  generateStrategyReaction,
  getChapterProgress,
  getCurrentChapter,
  getDialogueVoice,
  getGMPhilosophy,
  getOnboardingResult,
  getManagerStyleModifier,
  getNextChapter,
  getOwnerPersonalityProfile,
  identifyExtensionPriorities,
  identifyLeagueThreats,
  identifyPositionNeeds,
  identifyStarPlayers,
  isOnboardingComplete,
  profileKeyCoaches,
  profileTopProspects,
  rankStrategicPriorities,
  scoutDivisionRival,
  selectAGM,
  selectAGMInFlow,
  setPhilosophyChoiceInFlow,
  setScoutingHireInFlow,
  setStaffHiresInFlow,
  summarizeContractSituation,
  toAssistantGMProfile,
} from './onboarding/index.js';
export type {
  AGMCandidate,
  AGMCandidateId,
  AGMBackground,
  AGMPhilosophy,
  AGMPersonality,
  AGMStaffOpinion,
  AllChapterData,
  AppliedScoutingHire,
  AppliedStaffHires,
  AssistantGMBackground,
  AssistantGMPersonality,
  AssistantGMProfile,
  BaseballPhilosophy,
  BudgetOverview,
  DayOneBudgetAllocation,
  DayOneCrisis,
  DayOneCrisisResponseOption,
  DayOneCrisisType,
  DayOneDefaults,
  DayOneNarrativeContext,
  DayOneNarrativePack,
  DayOneOpeningBullpenPlan,
  DayOneOpeningPlan,
  DayOneOrgReview,
  DayOneOrgTier,
  DayOneProjectedImpact,
  DayOnePromotionStance,
  DayOneTeamCard,
  DayOneTeamCardInput,
  DayOneTeaser,
  ChapterAssessmentData,
  ChapterChoiceValue,
  ChapterChoices,
  ChapterProgress,
  ChapterScript,
  ChoiceReaction,
  CoachProfile,
  CoachingTip,
  ContractSituation,
  DecisionCoaching,
  DecisionPoint,
  DialogueLine,
  DialogueTone,
  ExtensionPriority,
  FarmAssessment,
  FinancialContext,
  FinancialFlexibility,
  FinancialPlaybook,
  GMPhilosophy,
  LineupAnalysis,
  DialogueVoice,
  ManagerStyle,
  ManagerStyleModifier,
  OnboardingFlowState,
  OnboardingResult,
  OnboardingTeamContext,
  OnboardingPressConferenceBriefing,
  OnboardingPressConferenceContext,
  OnboardingChapter,
  OnboardingChapterConfig,
  OnboardingHighlight,
  OnboardingScript,
  OnboardingScriptContext,
  OnboardingState,
  OpeningStatementOption,
  OwnerMeetingBriefing,
  OwnerMeetingContext,
  OwnerPersonality,
  PayrollBreakdown,
  PipelineHealth,
  PositionNeed,
  PersistedScoutingDirector,
  ProspectProfile,
  QuickReferenceCard,
  RevisedChapterScript,
  RevisedOnboardingScript,
  RevisedOnboardingScriptContext,
  RevisedChapterConfig,
  RevisedChapterId,
  RosterAssessment,
  RivalReport,
  ScoutingDirectorCandidate,
  ScoutingBriefing,
  ScoutingBriefingContext,
  ScoutingHiringSlate,
  SeasonStrategyBriefing,
  SeasonStrategyContext,
  SeasonStrategyOption,
  StaffCandidate,
  StaffEvaluation,
  StaffHireChoices,
  StaffHiringSlate,
  StaffStrengths,
  StarPlayerProfile,
  StrategicPriority,
  ThreatAssessment,
  VoiceStyle,
} from './onboarding/index.js';

// Scouting
export {
  generateScout,
  generateScoutingStaff,
  scoutPlayer,
  combineReports,
  getTeamScoutingAccuracy,
  generateScoutNotes,
  DEFAULT_IFA_BONUS_POOL,
  IFA_POOL_MIN,
  IFA_POOL_MAX,
  scoutQualityToAccuracy,
  getInternationalScoutAccuracy,
  generateIFAPool,
  createInternationalScoutingState,
  getAvailableIFAProspects,
  getRemainingIFABudget,
  scoutIFAProspect,
  tradeIFABonusPool,
  convertIFAProspectToPlayer,
  signIFAProspect,
  generateScoutConflict,
  resolveScoutConflicts,
} from './scouting/index.js';
export type {
  ScoutBias,
  Scout,
  ScoutReport,
  ScoutConflict,
  ScoutOpinion,
  ScoutOpinionSource,
  InternationalRegion,
  InternationalNationality,
  IFAProspectStatus,
  InternationalProspect,
  IFATeamBudget,
  InternationalScoutingReport,
  IFAScoutingHistoryEntry,
  InternationalScoutingState,
  SignIFAProspectResult,
} from './scouting/index.js';
export {
  buildMultiScoutConsensus,
  calculateScoutAccuracy,
  estimateAttributeWithUncertainty,
  generateScoutLearningEvent,
  updateScoutConfidence,
} from './scouting/scoutLearning.js';
export type {
  ActualOutcome,
  AttributeEstimate,
  ConsensusAgreementLevel,
  ConsensusReport,
  ScoutAccuracyProfile,
  ScoutBiasDirection,
  ScoutLearningEvent,
  ScoutObservation,
  ScoutPrediction,
  ScoutProfile,
} from './scouting/scoutLearning.js';

// Draft
export {
  generateDraftClass,
  rankProspects,
  DRAFT_CLASS_SIZE,
  DRAFT_ROUNDS,
  NUM_TEAMS,
  determineDraftOrder,
  aiSelectPick,
  evaluateTeamNeeds,
  simulateFullDraft,
  scoutDraftProspect,
  resolveDraftSigning,
  PROTECTED_TOP_TEN_PICK_COUNT,
  createDefaultDraftPickOwnership,
  tradeDraftPickOwnership,
  awardCompensatoryPick,
  forfeitHighestEligiblePick,
  buildDraftPickSlots,
} from './draft/index.js';
export type {
  DraftProspect,
  DraftProspectBackground,
  DraftClass,
  DraftPick,
  DraftResult,
  DraftScoutingReport,
  DraftSigningOutcome,
  DraftPickOwnership,
  DraftPickDescriptor,
  DraftCompensatoryPick,
  DraftCompensatoryPickAward,
  DraftPickSlot,
} from './draft/index.js';

// Trade
export {
  evaluatePlayerTradeValue,
  comparePackages,
  assignGMPersonality,
  evaluateTradeProposal,
  generateAITradeOffers,
  generateDeadlineTimeline,
  getDeadlineEventsForDay,
  generateBiddingWar,
  resolveDeadlineBuzzerBeater,
  executeTrade,
  generateTradeId,
  MAX_NEGOTIATION_ROUNDS,
  PENDING_EXPIRE_DAYS,
  INSTANT_REJECT_THRESHOLD,
  COUNTER_RANGE_LOW,
  COUNTER_RANGE_HIGH,
  initiateNegotiation,
  advanceNegotiation,
  resolveNegotiation,
  generateNegotiationDialogue,
  calculateCounterOffer,
  isNegotiationComplete,
} from './trade/index.js';
export type {
  PlayerTradeValue,
  PackageComparison,
  GMPersonality,
  TradeStatus,
  TradeProposal,
  TradeResult,
  DeadlineEventType,
  DeadlineEvent,
  DeadlineContext,
  BiddingRound,
  BiddingWar,
  BuzzerBeaterResult,
  NegotiationProposal,
  NegotiationContext,
  NegotiationPhase,
  NegotiationDialogue,
  CounterOffer,
  CounterOfferResult,
  NegotiationState,
  NegotiationResponse,
  NegotiationOutcome,
} from './trade/index.js';
export {
  detectTradeCascades,
  evaluateCondition,
  evaluateMultiTeamFairness,
  generateConditionalClause,
  generateMultiTeamTradeNarrative,
  proposeMultiTeamTrade,
} from './trade/multiTeamTrade.js';
export type {
  CascadeEvent,
  CompletedTrade,
  ConditionOutcome,
  ConditionalContext,
  FairnessAssessment,
  MultiTeamProposal,
  MultiTeamTradeResult,
  PendingTrade,
  TradeCondition,
  TradeConditionType,
  TradeParticipant,
  TradeParticipantRole,
} from './trade/multiTeamTrade.js';

// Roster Management
export {
  MLB_ROSTER_LIMIT,
  FORTY_MAN_LIMIT,
  MIN_PITCHERS,
  MIN_POSITION_PLAYERS,
  buildRosterState,
  validateRoster,
  executeRosterAction,
  promotePlayer,
  demotePlayer,
  dfaPlayer,
  getMLBRosterCount,
  get40ManCount,
  needsRosterMove,
  getNextLevel,
  autoFillMLBRoster,
} from './roster/index.js';
export type {
  RosterAction,
  RosterTransaction,
  RosterState,
  RosterValidation,
} from './roster/index.js';

// Offseason
export {
  OFFSEASON_PHASES,
  createOffseasonState,
  getOffseasonLength,
  advanceOffseasonDay,
  skipCurrentPhase,
  recordArbitration,
  recordTenderDecisions,
  recordExtensionResults,
  recordQualifyingOfferResults,
  recordCoachChange,
  recordFASigning,
  recordDraftPicks,
  recordIFASigning,
  recordRetirements,
  autoResolveTenderNonTender,
  determineRetirements,
  summarizeOffseason,
} from './roster/index.js';
export type {
  OffseasonPhase,
  OffseasonState,
  PhaseResults,
  ArbitrationResult,
  ExtensionPhaseResult,
  QualifyingOfferPhaseResult,
  CoachChangeResult,
  FASigningResult,
  DraftPickResult,
  IFASigningResult,
  RetirementResult,
  OffseasonSummary,
} from './roster/index.js';

// Free Agency
export {
  calculateMarketValue,
  getDemandLevel,
  projectContractYears,
  createFreeAgencyMarket,
  calculateQualifyingOfferSalary,
  getQualifyingOfferEligiblePlayers,
  issueQualifyingOffer,
  resolveQualifyingOffer,
  shouldIssueQualifyingOffer,
  generateAIOffer,
  simulateFADay,
  simulateFullFreeAgency,
  makeUserOffer,
  getTopFreeAgents,
} from './roster/index.js';
export type {
  FreeAgent,
  ContractOffer,
  FreeAgencyMarket,
  FreeAgencyAttractiveness,
  RelationshipBidContext,
  QualifyingOfferResolution,
} from './roster/index.js';
export {
  AFFILIATE_LEVELS,
  AFFILIATE_SCHEDULE_LENGTHS,
  EXPANDED_MLB_ROSTER_LIMIT,
  SEPTEMBER_EXPANDED_ROSTER_DAYS,
  ROOKIE_AFFILIATE_START_DAY,
  createMinorLeagueState,
  accrueServiceTimeDay,
  consumeOptionYear,
  buildWaiverPriority,
  placeOnWaivers,
  claimOffWaivers,
  isExpandedRosterWindow,
  getActiveRosterLimit,
  getRosterComplianceIssues,
  getPromotionCandidates,
  getMinorLeagueProgression,
  recordMinorLeagueStats,
  simulateAffiliateDay,
} from './roster/index.js';
export type {
  AffiliateLevel,
  AffiliatePlayerStats,
  AffiliateState,
  WaiverClaim,
  AffiliateBoxScore,
  MinorLeagueState,
  MinorLeagueMutationResult,
  WaiverClaimResult,
  RosterComplianceIssue,
  PromotionCandidate,
} from './roster/index.js';
export {
  calculateRule5EligibleAfterSeason,
  createRule5Session,
  estimateBackfilledRule5EligibilityAfterSeason,
  lockRule5ProtectionAudit,
  makeRule5Selection,
  passRule5DraftTurn,
  toggleRule5Protection,
} from './roster/index.js';
export type {
  Rule5ActionResult,
  Rule5EligiblePlayer,
  Rule5Obligation,
  Rule5OfferBackState,
  Rule5Selection,
  Rule5SessionState,
} from './roster/index.js';

// Narrative
export {
  generateNews,
  generateNewsId,
  checkMilestones,
  generateStandingsNews,
  getUnreadNews,
  markAsRead,
  deduplicateNews,
  generateSeasonRecap,
  generateRetirementNews,
  buildTradeConsequenceBundle,
  buildSigningConsequenceBundle,
  buildPostseasonConsequenceBundle,
  buildRetirementConsequenceBundle,
  buildTradeAftermathChain,
  appendConsequenceWatchers,
  evaluateConsequenceWatchers,
  calculateRushingRisk,
  calculateFanSentiment,
  generatePlayByPlay,
  generateGameHighlights,
  generateGameRecap,
  SITUATION_CONTEXTS,
  generateEnhancedPlayByPlay,
  generateDraftCommentary,
  generateDraftBuzz,
  generateDraftPickPreview,
  generateDraftGrades,
  deriveTradeDeadlineMode,
  generateTradeDialogue,
  generateTradeChatter,
  generateTickerEntries,
  pruneTickerFeed,
  detectNewStoryArcs,
  advanceStoryArcs,
  detectBreakoutCountdowns,
  generateDebutFlashback,
  generatePressConference,
  generateInteractivePressConference,
  selectPressConferenceTopic,
  generateEnhancedPressConference,
  evaluatePressConferenceResponse,
  generateHoldoutBriefing,
  generateHoldoutResolutionBriefing,
  generateExtensionSignedBriefing,
  generateRebuildAnnouncementBriefing,
  generateOffseasonHeadline,
  generateSeasonRecapNarrative,
  AWARD_CAPSTONE_BRANCH_VARIANTS,
  pickAwardCeremonyLine,
  resolveAwardCapstoneBranch,
  HOF_CAPSTONE_BRANCH_VARIANTS,
  pickHallOfFameInductionSummary,
  resolveHallOfFameBranch,
  RETIREMENT_CAPSTONE_BRANCH_VARIANTS,
  pickDebutPressLine,
  pickFarewellTourLine,
  pickJerseyRetirementLine,
  pickRetirementSpeechLine,
  resolveDebutPressBranch,
  resolveFarewellTourBranch,
  resolveJerseyRetirementBranch,
  resolveRetirementBranch,
  EVENTS_PER_MONTH_MIN,
  EVENTS_PER_MONTH_MAX,
  EVENT_WEIGHTS,
  generateMonthlyLeagueEvents,
  evaluateEventRippleEffects,
  generateLeagueEventNarrative,
} from './narrative/index.js';
export type {
  NewsPriority,
  NewsTag,
  NewsCategory,
  NewsItem,
  MomentType,
  Moment,
  GameEvent,
  OwnerDecisionDelta,
  PlayerMoraleDelta,
  ConsequenceBundle,
  TradeConsequenceContext,
  SigningConsequenceContext,
  PostseasonConsequenceContext,
  RetirementConsequenceContext,
  UserPostseasonOutcome,
  TradeAftermathChainContext,
  EvaluateConsequenceWatchersContext,
  EvaluateConsequenceWatchersResult,
  RushingRisk,
  FanSentimentContext,
  GameHighlight,
  EnhancedPlayByPlayEntry,
  PlayByPlayContext,
  DraftNarrativeTone,
  DraftNarrativeProspect,
  DraftNarrativePick,
  DraftNarrativeCurrentPick,
  DraftCommentaryEntry,
  DraftBuzzItem,
  DraftPickPreview,
  DraftTeamGrade,
  TradeDeadlineMode,
  TradeNegotiationType,
  TradeDialogue,
  TradeChatterItem,
  TickerGenerationContext,
  TickerInjuryContext,
  TickerMilestoneContext,
  TickerProspectCallupContext,
  TickerRecordWatchContext,
  TickerRumorCandidate,
  TickerScoreContext,
  TickerStandingsChangeContext,
  TickerTradeContext,
  StoryArcSnapshot,
  BreakoutCountdown,
  BreakoutCountdownSnapshot,
  PressConferenceContext,
  PressConferenceResponse,
  InteractivePressConference,
  PressConferenceResponseTone,
  PressConferenceSeasonRange,
  PressConferenceTopicCategory,
  PressConferenceTopicContext,
  EnhancedPressConferenceResponse,
  PressConferenceTopic,
  EnhancedPressConference,
  PressConferenceOutcome,
  HoldoutCoverageContext,
  HoldoutBriefing,
  AwardAcquisitionType,
  AwardCapstoneBranch,
  AwardCapstonePoolId,
  AwardWinnerRole,
  HallOfFameCapstoneBranch,
  HallOfFameInductionType,
  DebutPressBranch,
  FarewellTourBranch,
  JerseyRetirementBranch,
  RetirementCapstoneBranch,
  RetirementCapstonePoolId,
  RetirementSpeechBranch,
  ExtensionSignedBriefingContext,
  RebuildAnnouncementBriefingContext,
  LeagueEventType,
  LeagueEventTeamSnapshot,
  LeagueEventContext,
  TradeMarketShiftEffectData,
  ProspectMarketShiftEffectData,
  GMResetEffectData,
  SellerSignalEffectData,
  BudgetShiftEffectData,
  RevenueShiftEffectData,
  InternationalMarketShiftEffectData,
  DraftPickPenaltyEffectData,
  ExpansionUncertaintyEffectData,
  LeagueEventEffectData,
  LeagueEvent,
  TradeMarketShiftRippleEffect,
  ProspectMarketShiftRippleEffect,
  GMResetRippleEffect,
  SellerSignalRippleEffect,
  BudgetShiftRippleEffect,
  DraftPickPenaltyRippleEffect,
  InternationalMarketShiftRippleEffect,
  RevenueShiftRippleEffect,
  ExpansionUncertaintyRippleEffect,
  RippleEffect,
} from './narrative/index.js';

// Sharing
export {
  generateDynastyCard,
  generateSeasonRecapCard,
  generateChampionshipCard,
  calculateDynastyLeaderboardScore,
} from './sharing/index.js';

// Invariants
export {
  checkUniquePlayerAssignment,
  checkRosterLimits,
  checkStandingsConsistency,
  checkRatingBounds,
  runInvariantChecks,
} from './invariants/checker.js';
export type {
  InvariantSeverity,
  InvariantViolation,
  InvariantCheckResult,
} from './invariants/checker.js';

// Scenarios
export {
  SCENARIO_LIBRARY,
  getScenarioById,
  readScenarioRecord,
  applyScenarioOverrides,
  evaluateScenarioProgress,
  completeScenario,
  SCENARIO_OBJECTIVES,
  getScenarioObjectives,
  evaluateObjectiveProgress,
} from './scenarios/index.js';
export type {
  ScenarioObjective,
  ScenarioObjectiveSet,
  ObjectiveProgressContext,
} from './scenarios/index.js';
