import {
  Home,
  Users,
  Briefcase,
  Trophy,
  Clock,
  Smile,
  Gauge,
  Flame,
  ListOrdered,
  ArrowLeftRight,
  Handshake,
  UserPlus,
  FileText,
  Scale,
  Building2,
  Search,
  TrendingUp,
  Newspaper,
  HeartPulse,
  Medal,
  Star,
  Zap,
  BarChart3,
  Construction,
  Sprout,
  DollarSign,
  ScrollText,
  Mic,
  Check,
  Ban,
  AlertTriangle,
  SkipForward,
  Target,
  type LucideIcon,
} from 'lucide-react';

/** Lucide icon mappings for all game icon names. */
export const ICON_MAP: Record<IconName, LucideIcon> = {
  home:         Home,
  team:         Users,
  frontOffice:  Briefcase,
  league:       Trophy,
  history:      Clock,
  casual:       Smile,
  standard:     Gauge,
  hardcore:     Flame,
  lineup:       ListOrdered,
  rosterMoves:  ArrowLeftRight,
  trades:       Handshake,
  freeAgency:   UserPlus,
  draft:        FileText,
  extensions:   ScrollText,
  arbitration:  Scale,
  minorLeagues: Building2,
  scouting:     Search,
  development:  TrendingUp,
  news:         Newspaper,
  injury:       HeartPulse,
  medal:        Medal,
  star:         Star,
  fire:         Flame,
  lightning:    Zap,
  stats:        BarChart3,
  construction: Construction,
  seedling:     Sprout,
  people:       Users,
  money:        DollarSign,
  scroll:       ScrollText,
  microphone:   Mic,
  checkmark:    Check,
  blocked:      Ban,
  warning:      AlertTriangle,
  skip:         SkipForward,
  target:       Target,
};

/** @deprecated Use ICON_MAP + MbdIcon instead. Kept for backward compatibility. */
export const GAME_ICONS = {
  home:         { path: '/icons/home.png',         fallback: 'H' },
  team:         { path: '/icons/team.png',         fallback: 'T' },
  frontOffice:  { path: '/icons/frontOffice.png',  fallback: 'FO' },
  league:       { path: '/icons/league.png',       fallback: 'LG' },
  history:      { path: '/icons/history.png',      fallback: 'HI' },
  casual:       { path: '/icons/casual.png',       fallback: 'C' },
  standard:     { path: '/icons/standard.png',     fallback: 'ST' },
  hardcore:     { path: '/icons/hardcore.png',      fallback: 'HC' },
  lineup:       { path: '/icons/lineup.png',       fallback: 'LU' },
  rosterMoves:  { path: '/icons/rosterMoves.png',  fallback: 'RM' },
  trades:       { path: '/icons/trades.png',       fallback: 'TR' },
  freeAgency:   { path: '/icons/freeAgency.png',   fallback: 'FA' },
  draft:        { path: '/icons/draft.png',        fallback: 'DR' },
  extensions:   { path: '/icons/extensions.png',   fallback: 'EX' },
  arbitration:  { path: '/icons/arbitration.png',  fallback: 'AR' },
  minorLeagues: { path: '/icons/minorLeagues.png', fallback: 'ML' },
  scouting:     { path: '/icons/scouting.png',     fallback: 'SC' },
  development:  { path: '/icons/development.png',  fallback: 'DV' },
  news:         { path: '/icons/news.png',         fallback: 'N' },
  injury:       { path: '/icons/injury.png',       fallback: '+' },
  medal:        { path: '/icons/medal.png',         fallback: 'M' },
  star:         { path: '/icons/star.png',         fallback: '*' },
  fire:         { path: '/icons/fire.png',         fallback: 'F' },
  lightning:    { path: '/icons/lightning.png',     fallback: 'Z' },
  stats:        { path: '/icons/stats.png',        fallback: '#' },
  construction: { path: '/icons/construction.png', fallback: 'WK' },
  seedling:     { path: '/icons/seedling.png',     fallback: 'SD' },
  people:       { path: '/icons/people.png',       fallback: 'PP' },
  money:        { path: '/icons/money.png',        fallback: '$' },
  scroll:       { path: '/icons/scroll.png',       fallback: 'SL' },
  microphone:   { path: '/icons/microphone.png',   fallback: 'MC' },
  checkmark:    { path: '/icons/checkmark.png',    fallback: 'OK' },
  blocked:      { path: '/icons/blocked.png',      fallback: 'X' },
  warning:      { path: '/icons/warning.png',      fallback: '!' },
  skip:         { path: '/icons/skip.png',         fallback: '>>' },
  target:       { path: '/icons/target.png',       fallback: 'TG' },
} as const;

export type IconName = keyof typeof GAME_ICONS;
